version: "3"

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27017"
    cap_add:
      - AUDIT_WRITE
      - SETGID
      - SETUID
    cap_drop:
      - ALL
